### ISSUE TITLE
A string is detected as not added and also need to be removed.

### ISSUE THREAD

**Issue by realBoubli** [pixelartgirl/Aseprite-Translation-Manager#1]
Tried your app, and there is a little bug. (oh no :c )
Only a single string is detected both as not added and as not removed. Quite strange. I can give you [the .ini files i used](https://github.com/pixelartgirl/Aseprite-Translation-Manager/files/8693945/strings.zip) (including my latest changes OMG) if you want to debug your app.
![Not added](https://user-images.githubusercontent.com/49991411/168449070-597c40b6-8b21-4704-9201-58da98ffe051.png)
![Not removed](https://user-images.githubusercontent.com/49991411/168449077-8f32e8fc-e23b-493c-892c-1fed417c0978.png)

**Comment by pixelartgirl** [comment]
Hi

Thanks for trying my app!
I see it runs fine on windows 11. I have windows 10.

My file parser is extremely sensitive and also will detect a wrong space!

Look in your en.ini file: somebody have put by mistake in the file en.ini an extra space behind select_palette_colors and before "=".
This extra space is not in fr.ini.
This means my parser says en.ini has not a string without space and fr.ini has not a string with a space...

Please remove the extra space in en.ini and save it and re-scan.
All weird things you should be able to fix by looking at the line in the INI files.
I can make several tests to let my file parser skip this but I designed it to compare the strings 100%. So this means 1 space more is not the same string. So this detects any typo ANYWHERE!

From what version of aseprite is the en.ini? Aseprite's parser will skip spaces probably.

Feel free to report any bug.

**Comment by pixelartgirl** [comment]
Click the red link to open your ini file to edit.
This will be in next manual update.
