### ISSUE TITLE
Please publish the source not the binary

### ISSUE THREAD

**Issue by EmmanuelMess** [pixelartgirl/Aseprite-Translation-Manager#2]
You can add binaries as releases.

**Comment by pixelartgirl** [comment]
Why do you need the source code?
Do you want to add features? You can report bugs and I fix them (if possible).

This small program has only 1 goal: compare en.ini to your own translation ini file. This works 100 % now.
I don't plan adding features which have nothing to do with this main feature.

**Comment by EmmanuelMess** [comment]
> Why do you need the source code?

Not need, but some people prefer to compile the software themselves or read the code.

>  I don't plan adding features which have nothing to do with this main feature.

With the source others can fork it later if the project stops being supported.
