### ISSUE TITLE
Please publish a linux version

### ISSUE THREAD

**Issue by EmmanuelMess** [pixelartgirl/Aseprite-Translation-Manager#3]
Please provide a linux version of the software too.

**Comment by pixelartgirl** [comment]
This software is written using Windows Forms UI which is Windows only. It can't be compiled for Linux or Mac.

I know there is a project called Wine to run windows programs on Linux but I don't use Linux myself.

The program use .NET Framework 4.8 if this can help you.

**Comment by EmmanuelMess** [comment]
Why wasn't linux considered in the design phase?

**Comment by pixelartgirl** [comment]
Because I don't use Linux and don't know anything about it.
