### ISSUE TITLE
Second link to edit is not working

### ISSUE THREAD

**Issue by FabianoIlCapo** [pixelartgirl/Aseprite-Translation-Manager#4]
When I click on the second red link, the one that's supposed to open my translated .ini file, nothing happens.
The link appears to be clickable, but it just doesn't react in any way.
The first link works with no problem, and opens up Notepad with the file ready.

![link not working](https://user-images.githubusercontent.com/42750867/168475047-dd9d8673-4264-4563-9e05-d5bd2050c958.JPG)

Even if I put the same file in both slots, the second link still doesn't work.

**Comment by pixelartgirl** [comment]
Download v1.2 please.
